# Generated by Django 4.0.3 on 2022-04-15 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_customer_id_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='frenchieuser',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
