# Generated by Django 4.0.3 on 2022-04-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customer_name_alter_frenchieuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
