# Generated by Django 4.0.3 on 2022-04-15 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0007_remove_product_category_alter_albumphoto_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
