# Generated by Django 4.0.3 on 2022-04-15 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_albumphoto_name_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
